name: Update database

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  NODE_VERSION: 20.17.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_db:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: Install, Build & Run
        run: |-
          echo "::group::Install dependencies"
          yarn
          echo "::endgroup::"
          echo "::group::Build NodeJS command"
          yarn build
          echo "::endgroup::"
          .github/scripts/update_db.sh --ci

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: db
          path: |
            db/out.csv
            db/out.json
            db/lastrun.txt

      - name: Commit report
        run: |
          OLD_RUN_TIME=$(cat db/lastrun.txt | head -1 | sed 's/\r$//')
          git config --global user.name 'Auto Update'
          git config --global user.email 'senorihl@users.noreply.github.com'
          git add db/lastrun.txt
          git add db/out.csv
          git add db/out.json
          git commit -m "auto update on $OLD_RUN_TIME"
          git push
