name: Release package

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NODE_VERSION: 20.17.0

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: yarn
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies & build
      run: yarn && yarn build
    - uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}
        provenance: true
        access: public